name:                flashcards
version:             0.1.0.0
github:              "FishyMcSwish/flashcards"
license:             BSD3
author:              "Grant Maki"
maintainer:          "grantmaki@pm.me"
copyright:           "2021 Grant Maki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/FishyMcSwish/flashcards#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-tabs
  dependencies:
  - yesod

executables:
  flashcards-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flashcards
    - yesod

tests:
  flashcards-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flashcards
